services:
  - type: web
    name: agnidrishti-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: FIRMS_MAP_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FASTAPI_URL
        value: https://agnidrishti-ml.onrender.com
      - key: FRONTEND_URL
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_EMAIL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_NAME
        value: "AgniDrishti Alert System"
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: FAST2SMS_KEY
        sync: false
      - key: SMS_MOCK
        value: "false"
